### ISSUE TITLE
Баг атаки ближнего боя и проверки на нахождение на земле

### ISSUE THREAD

**Issue by krbroman** [hypnospinner/darklight#4]
1) Через раз работает прыжок (Я думаю, это связано с Movement Smoothing)
2) Я заметил баг-фичу: если встать возле стены и быстро нажимать a/d и space, то есть шанс, что персонаж отскочит от нее и попадет туда, куда обычным прыжком не смог бы попасть. (Мне кажется, это прикольная фишка, возможно, ее стоит доработать)
3) Проблему с уничтожением блоков по вертикали в ближнем бою вроде бы исправил, но я уверен, что есть решение лучше

**Comment by hypnospinner** [comment]
1. и 2. связаны скорее с тем как идет проверка на isGrounded и какие объекты для этого используются. Советую все это пересмотреть.
3. Опиши баг подробнее, какие кнопки, какое поведение, какая последовательность

**Comment by DenisMakarov** [comment]
Еще можно прыгнуть в воздухе во время падения, если сьехать с блоков и сразу пробел нажать

**Comment by hypnospinner** [comment]
Fix в том, чтобы поставить ground checkers на +-0.5 (примерно)

**Comment by hypnospinner** [comment]
Баги были пофикшены @DenisMakarov
